### ISSUE TITLE
CPU requests change to `0` when limits introduced.

### ISSUE THREAD

**Issue by varditn** [travelaudience/aerospike-operator#15]
When setting k8s resources limits on AS pod that doesn't have requests configured manually, CPU requests change to `0` from the default `1` value.
  ```
  resources:
      limits:
        cpu: 1300m
        memory: 1395864371200m
      requests:
        cpu: "0"
        memory: 1Gi
```
